config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :pages
  resources :polls
  resources :feedbacks
  
  resources :users do
    collection do
      get 'search_user'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :poll
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :state
  belongs_to :user
  has_many  :feedbacks

end

app/models/state.rb
class State < ApplicationRecord
  has_many :polls
end

app/models/user.rb
class User < ApplicationRecord
  has_many :polls
  accepts_nested_attributes_for :polls
  validates :rut, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  def index
    @user = User.all
  end

  def new
    @poll = Poll.find_by_id(params[:id])
    @feedback = Feedback.new
    render layout: 'dashboard'
  end

  def create
    @feedback = Feedback.new(feedback_params)
    user = User.joins(:polls).select("users.id").where("polls.id = #{feedback_params[:poll_id]}").group('users.id').first
    flash[:success] = "Se envio tu respuesta!!!"
    @feedback.save
    redirect_to poll_path(user.id)
  end

  private

  def feedback_params
    params.require(:feedback).permit(:poll_id, :enviado_por, :respuesta)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  def index
    @estado = State.includes(:polls).group(:id).pluck( "states.descripcion, count(polls.id)" )
    @genero = User.group(:genero).count
    render layout: 'dashboard'
  end

  def show
    @user = User.find_by_id(params[:id])
    render layout: 'dashboard'
  end

  def new
    @user = User.new
    @user.polls.build
  end

  def create
    if User.exists?( :rut => poll_create[:rut] )
      @user = User.find_by_rut( poll_create[:rut] )
      @user.update_attributes(poll_create)
      flash[:success] = "Usuario registrado, se agrega respuesta!!!"
    else
      @user = User.new(poll_create)
      @user.save
      flash[:alert] = "Usuario no registrado, se agrega respuesta!!!"
    end
    redirect_to new_path
  end


  private
    def poll_create
      params.require(:user).permit(:nombre, :fnacimiento, :rut, :genero, polls_attributes: [:state_id, :motivo, :user_id])
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
    render layout: 'dashboard'
  end

  def new
    @users = User.new
  end

  def search_user
    @user = User.find_by_rut(params[:rut])
      if @user != nil
        render :json => @user
      else
        render :json => { :errors => @user.errors }, :status => 422
      end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
      case level
        when "notice" then return "alert alert-info"
        when "success" then return "alert alert-success"
        when "error" then return "alert alert-warning"
        when "alert" then return "alert alert-danger"
      end
  end

end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/feedbacks/index.html.erb
<h1>Feedback</h1>

app/views/feedbacks/new.html.erb
<h3>Entregar feedback</h3>

<table>
  <tr>
      <td>Nombre Completo :</td>
      <td><%= @poll.user.nombre %></td>
  </tr>
  <tr>
      <td>Rut :</td>
      <td><%= @poll.user.rut %></td>
  </tr>
  <tr>
      <td>Estado :</td>
      <td><%= @poll.state.descripcion %></td>
  </tr>
</table>

<hr>
<h4>Ultimas respuestas</h4>
  <% @poll.feedbacks.each do |p| %>
  <%= p.enviado_por%> -> <%= p.respuesta %> <br>
  <% end %>
<hr>
<%= form_for @feedback do |f| %>
  <%= f.hidden_field :poll_id, :value => @poll.id %>

  <div class="form-group col-md-3">
    <%= f.label :enviado_por, "Persona que responde" %><br>
    <%= f.select :enviado_por, [['Jefe', 'Jefe'], ['Supervisor', 'Supervisor'], ['Otro..', 'Otro']], {}, :class=> "form-control" %>
  </div>

  <div class="form-group col-md-3">
    <%= f.label :respuesta, "Respuestas" %><br>
    <%= f.text_area :respuesta, cols: 100, rows: 10 %>
  </div>

  <%= f.submit "Enviar", :class => "btn btn-primary" %>

<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ess">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>¿How Are You?</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'semaforo.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :javascript_includes %>
  </head>
  <body>


      <div class="container">
        <%= yield %>
      </div>

  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html lang="ess">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>¿How Are You?</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'semaforo.ico' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <%= yield :javascript_includes %>
  </head>

  <body id="page-top">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
      <div class="container">
        <%= link_to 'estado de ánimo', root_path, remote: true, class: "navbar-brand js-scroll-trigger" %>
        <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-0 mx-lg-1">
              <%= link_to 'encuesta', new_poll_path, remote: true, class: "nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <%= link_to 'resultados', users_path, remote: true, class: "nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <%= link_to 'gráficos', polls_path, remote: true, class: "nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Header -->

      <div class="container">
        <header class="masthead">
            <%= yield %>
        </header>
      </div>
      <!-- Footer -->
      <footer class="footer text-center">
        <div class="container">

        </div>
      </footer>

  </body>
</html>

app/views/pages/index.html.erb
    <h1 class="text-uppercase mb-0">
      How Are You?
    </h1>
    <hr class="star-light">
    <h2 class="font-weight-light mb-0">¿Como estás?</h2>

app/views/polls/index.html.erb
<h3>Por estado</h3>
<%= pie_chart @estado,
    colors: ['#FFFF00', '#FF6347', '#32CD32' ]
%>
<hr>
<h3>Por genero</h3>
<%= column_chart @genero,
    colors: ['#1E90FF', '#20B2AA' ]
%>

app/views/polls/new.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>
<div class="justify-content-md-center">
            <div class="col align-self-center">
                <h1>¿How Are You?</h1>
            </div>
            <div class="col align-self-end">
                <p>¿Como Estás?</p>
            </div>
</div>
<div class="justify-content-md-center">
<%= form_for @user, :url => { :controller => "polls", :action => "create" } do |f| %>
  <div class="form-row justify-content-md-center">
    <div class="form-group col-md-4">
      <%= f.label :rut %>
      <%= f.text_field :rut, class: "form-control", placeholder: "12345678-9", maxlength: 10, :required => true %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :nombre, "Nombre Completo" %>
      <%= f.text_field :nombre, placeholder: "Ej: Juan Pérez", class: "form-control", maxlength: 255, size: 30, :required => true %>
    </div>
  </div>
  <br>
  <div class="form-row justify-content-md-center">
      <div class="form-group col-md-3">
        <%= f.label :fnacimiento, "Fecha de Nacimiento" %><br>
        <%= f.date_field :fnacimiento, :id => "fnacimiento", class: "form-control", :required => true%>
      </div>
      <div class="form-group col-md-3">
        <%= f.label :genero, "Género" %><br>
        <%= f.select :genero, [['Hombre', 'Hombre'], ['Mujer', 'Mujer'], ['Otro..', 'Otro']], {}, {:class => "form-control" } %>
      </div>
  </div>
<%= f.fields_for :polls do |ff| %>
  <%= ff.hidden_field :user_id%>
  <div id="custom-radios">
      <%= ff.collection_radio_buttons( :state_id, State.all, :id, :imagen
        ) do |b|
          b.label(:"id" => "label_color_#{b.object.id}") { image_tag(b.object.imagen) + b.radio_button }
        end
      %>
  </div>

  <div id="mensaje_motivo">
    <div id="motivo" class="collapse">
        <%= ff.label :motivo, "Seleccione un motivo" %></br>
        <%= ff.select :motivo, [['Laboral', 'Laboral'], ['Personal', 'Personal'], ['Ambos', 'Ambos']], {}, {:class => "form-control col-4"} %>
    </div>
<% end %>
  <div id="agregar">
    <%= f.submit "Agregar" , class: "btn btn-primary"%>
  </div>
</div>

<% end %>


<!-- The Modal -->

<div class="modal fade" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Ups, tenemos un problema...</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <!-- Modal body -->
        <div class="modal-body">
          RUT, ingresado no es correcto..!!
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>

      </div>
    </div>
</div>

app/views/polls/show.html.erb
<h3>Respuesta usuario : </h3>
Nombre: <%= @user.nombre %>
<br>
RUT: <%= @user.rut %>
<hr>
<table id="feedback_table" class="display responsive no-wrap" >
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Estado</th>
      <th>Motivo</th>
      <th>Feedback</th>
      <th>Acción</th>
    </tr>
  </thead>
  <tbody>
    <% @user.polls.each do |p| %>
      <tr>
        <td><%= p.created_at.strftime("%Y-%m-%d") %></td>
        <td><%= p.state.nombre %></td>
        <td><%= p.motivo %></td>
        <td><%= p.feedbacks.count %></td>
        <td>
          <%= link_to image_tag('respuesta.png'), new_feedback_path( :id => p.id ), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<h3>Participación de usuarios</h3>
<table id="feedback_table" class="display responsive no-wrap" >
  <thead>
    <tr>
      <th>Rut</th>
      <th>Nombre</th>
      <th>Respuestas</th>
      <th>Estados</th>
    </tr>
  </thead>
  <tbody>
    <% @user.each do |p| %>
      <tr>
        <td><%= p.rut %></td>
        <td><%= p.nombre %></td>
        <td><%= p.polls.count %></td>
        <td>
          <%= link_to image_tag('respuesta.png'), poll_path( p.id ), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>